chat/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import *

app_name = 'chat'

urlpatterns = [
	path('', chated, name='chat')
]

socset/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('site/', include('siteland.urls')),
    # path('chat/', include('chat.urls'))
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from django.contrib.auth import get_user_model
from markdown_deux import markdown

from django.contrib.contenttypes.models import ContentType

from django.contrib.auth.models import User

User = get_user_model()

class Photo(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
								on_delete=models.CASCADE)
	imageuser = models.FileField(upload_to='imageinst', 
						verbose_name='photouser')
	dataimg = models.DateTimeField(auto_now=True, 
									auto_now_add=False)
	photolike = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='post_likes')

	orphotoorvideo = models.BooleanField(default=False)

	text = models.TextField(null=True)

	def __unicode__(self):
		return self.imageuser
	# def get_like_url(self):
	# 	return reverse("likephoto", kwargs={"id": self.id})


class Chat(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
	 on_delete=models.CASCADE)
	useryou = models.ForeignKey(settings.AUTH_USER_MODEL,
	 on_delete=models.CASCADE,
	 related_name="useryou")
	message = models.TextField(null=True)
	datamessage = models.DateTimeField(auto_now=True, 
									auto_now_add=False)


	def __str__(self):
		return str(self.user)

	def get_like_url_photo(self):
		return reverse("listusers:likephoto", kwargs={"id": self.id})


class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	avatar = models.ImageField(upload_to='imageusers', verbose_name='Изображение')
	placework = models.TextField(default='Отсутствует')
	city = models.TextField(default='Отсутствует')
	friends = models.ManyToManyField(User, 
				related_name='is_friends',
				blank=True)

	followers = models.ManyToManyField(User, 
				related_name='is_following',
				blank=True)
	zayavkadruzya = models.ManyToManyField(User, 
			related_name='addingfriend',
			blank=True,)

	messagedo = models.ManyToManyField(User, 
				related_name='messagedo',
				blank=True)
	allmessagesstory = models.ManyToManyField(User, 
				related_name='allmessagesstory',
				blank=True)

	last_activity = models.DateTimeField(auto_now=True, 
				auto_now_add=False)

	user_online = models.BooleanField(default=False)


	def __unicode__(self):
		return self.user

	def user_get_absolute_url(self):
		return reverse("accounts:userdetail", kwargs={"id": self.id})


	def get_like_url(self):
		return reverse("foto:like-toggle", kwargs={"id": self.id})

	def get_api_like_url(self):
		return reverse("foto:like-api-toggle", kwargs={"id": self.id})



class Meta:
	verbose_name = 'Профиль'

chat/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from django.contrib.auth import get_user_model
from markdown_deux import markdown

from django.contrib.contenttypes.models import ContentType

from django.contrib.auth.models import User


class Chat(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	message = models.TextField()
	datamessage = models.DateTimeField(auto_now=True, 
									auto_now_add=False)

	def __str__(self):
		return str(self.user)

chat/forms.py
from django import forms
from .models import *

import os
import unittest

class ChatForm(forms.ModelForm):
    class Meta:
        model = Chat
        exclude = [""]

chat/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect

from django.contrib.auth import (
        authenticate,
        get_user_model,
        login,
        logout,
    )
from django.db.models import Q

# from .forms import *
from .models import *

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
import json
import urllib


def chated(request):
    pass
    # form = ChatForm(request.POST or None)
    # # messagerun = request.POST.get("runmessagehtml")

    # if request.method == "POST" and form.is_valid():
    #     data  = form.cleaned_data
    #     new_form = form.save()

    # return render(request, 'chat/chat.html', locals())

templates/chat/allchat.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    
 
  {% include 'stylesand.html' %}
    <title>FaceVkInsta</title>
  </head>
  <body>
    
    
<header>
{% include 'navbar.html' %}
</header>

<br><br><br><br>
    <div class="container">  
      <div class="row"> 
          
          
        <div class="col-lg-9 col-md-9 col-xs-12 leftprofile">
          <div class="leftprofilecolor">


          {% for d in chatstory %}
{% if d.user in request.user.userprofile.allmessagesstory.all %}
          <div class="allchat">
          <p>
<a href="{{ d.user_get_absolute_url }}chat/">
          {{ d.user.get_full_name }} 

  </a>
{% if d.user in request.user.userprofile.messagedo.all %}
<p class="inmessage">
  Пропущенное сообщение
</p>
{% endif %}
          </p>
          </div>
          <br><hr>

          {% endif %}
          {% endfor %}
          

        
        <br><br>
        <!-- <div class="friends">
          <p>Друзья <a style="margin-left: 10px;" href="/listusers/"> Найти ешё друзей</a></p>
          <hr>
          
      {% for users in zayavka_list %}
{% if users.user in request.user.userprofile.friends.all %}
          <div class="firendsOnlineList">
            <p>
            <a href="{{ users.user_get_absolute_url }}">
          {{ users.user.get_full_name }}</a>
          </p> 
            Бил в сети {{ users.last_activity|timesince}} назад<p>
          </div>
          <hr>
          {% endif %}
          {% endfor %}


        </div> -->
          <div class="chat"></div>

        </div>
      </div>

        <div class="col-lg-3 col-md-3 col-xs-12">
          <p class="">BANNER</p>
          <br>
 
        </div>
          
        

      </div>
    </div>

   

    <div style="margin-top: 1000px;"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/chat/chat.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
  <link rel="stylesheet" href="{% static 'css/chat.css' %}">

    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    
 
  {% include 'stylesand.html' %}

    
     <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>


    <title> Chat | FaceVkInsta</title>
  </head>
  <body>
    
    
<header>
    {% include 'navbar.html' %}
  </header>

<div style="margin-top: 80px;"></div>




    <div class="container">
      <div class="row">
        <div class="col-lg-8">

          <div>
            <p>{{ userobjchat.user.get_full_name }} |

      {% if userobjchat.user.userprofile.user_online %}
          <small style="color: #E58181;"> online</small>
          {% else %}
          <small>
          Бил в сети {{ userobjchat.user.userprofile.last_activity|timesince }} назад
          </small>
    {% endif %}
            </p>
            {% if userobjchat.user.userprofile.avatar %}
          <img class="imgfloatleft" 
          src="{{ userobjchat.user.userprofile.avatar.url }}">
            {% else %}
            <img class="imgfloatleft" 
          src="{% static 'img/default_avatar.png' %}">
          {% endif %}
          </div>
          
          <div id="msg-list-div" class="messpanel">
          <div id="messpanelchild">
            <br>

<!-- id="ul" -->
            <ul id="msg-list" class="ul list-group" >
     {% for mess in allmessages %}
    
  {% if mess.user == request.user %}
    {% if mess.useryou == userobjchat.user %}
     <li class="text-right mymsg">
                <p class="pright">
              {{ mess.message }} <br>
              <small>{{ mess.datamessage|date:"H:i" }} |
                <a class="menuclassmessage" 
          href="/chatdel/{{ mess.id }}/">
            <i class="fas fa-trash-alt"></i>
          </a>
              </small>
               </p>
            

            </li>
    

    {% endif %}
      {% else %}

        {% if mess.user == userobjchat.user %}
        {% if mess.useryou == request.user %}

              <li class="text-left yourmsg">
                <p class="pleft">
              {{ mess.message }}<br>
              <small>{{ mess.datamessage|date:"H:i" }}</small>
            </p>
            </li>

            {% endif %} <!-- mess.useryou = request.user -->

      {% endif %}
      {% endif %}
            
            {% empty %}
                    <li class="text-right">No messages yet!</li>
              
           {% endfor %}
            </ul>



            <br>
          </div>
          </div> <!-- ../ Mess Panel -->
          <br>
          

<form id="chat-form" method="post" 
action="/post/{{ userobjchat.id }}/">
            {% csrf_token %}
            <div id="chat-bottom" class="input-group"> 
     <textarea id="chat-msg" name="chat-msg"
     class="input" 
     wrap="soft | hard" 
     class="textmessage"></textarea>
<span class="input-group-btn">
  <button id="send" type="submit" class="input-addon">
  <img class="imgsend" src="{% static 'img/send.png' %}" 
  alt="">
</button>
</span>
</div>
</form>
        </div>



        <div class="col-lg-4">


          <ul id="msg-list" class="list-group listvsmg">
  {% for d in chatstory %}
{% if d.user in request.user.userprofile.allmessagesstory.all %}

           <li class="list-group-item itemhistorymsg">
            <a class="aclass" 
            href="{{ d.user_get_absolute_url }}chat/">

              <img class="usermyimg" 
      src="{{ d.user.userprofile.avatar.url }}" 
              alt="">
            {{ d.user.get_full_name }} 
 {% if d.user in request.user.userprofile.messagedo.all %}
<p class="inmessage">
  Пропущенное сообщение
</p>
{% else %}



{% for msgstory in messagestory %}
<p class="historymsg">

{% if msgstory.useryou == d.user %}
{{ msgstory.message|truncatechars:40 }} 

{% endif %}

{% if msgstory.useryou == request.user and msgstory.user == d.user %}

{{ msgstory.message|truncatechars:40 }}

{% endif %}

</p>
 {% endfor %}
  
 
{% endif %}
          
          </a>
          </li>

          {% endif %}
          {% endfor %}


          </ul>
        </div>
      </div>
    </div>

    <script>
      {% include 'chat/chat.js' %}
    </script>
  

 
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/chat/messages.html
{% for mess in allmessages %}
    
  {% if mess.user == request.user %}
    {% if mess.useryou == userobjchat.user %}
     <li class="text-right mymsg">
                <p class="pright">
              {{ mess.message }} <br>
              <small>{{ mess.datamessage|date:"H:i" }} |
                <a class="menuclassmessage" 
          href="/chatdel/{{ mess.id }}/">
            <i class="fas fa-trash-alt"></i>
          </a>
              </small>
               </p>
            

            </li>
    

    {% endif %}
      {% else %}

        {% if mess.user == userobjchat.user %}
        {% if mess.useryou == request.user %}

              <li class="text-left yourmsg">
                <p class="pleft">
              {{ mess.message }}<br>
              <small>{{ mess.datamessage|date:"H:i" }}</small>
            </p>
            </li>

            {% endif %} <!-- mess.useryou = request.user -->

      {% endif %}
      {% endif %}
            
            {% empty %}
                    <li class="text-right">No messages yet!</li>
              
           {% endfor %}

templates/chat/test.html
<!-- *************************************** -->




<br><br><br><br>
    <div class="container">  
      <div class="row"> 
          
          
        <div class="col-lg-9 col-md-12 col-xs-12 leftprofile">

        <div class="nameuserchat">
<div style="margin-top: 4px;"></div>
          
          {% if userobjchat.user.userprofile.avatar %}
          <img class="img-fluid img-thumbnail imgchat" 
          src="{{ userobjchat.user.userprofile.avatar.url }}">
            {% else %}
            <img class="img-fluid img-thumbnail imgchat" 
          src="{% static 'img/default_avatar.png' %}">
          {% endif %}


          <div class="namemessagetime">
        
         <p>  {{ userobjchat.user.get_full_name }} |</p>

          <p> 
  {% if userobjchat.user.userprofile.user_online %}
          <small style="color: #E58181;"> online</small>
          {% else %}
          <small>
          Бил в сети {{ userobjchat.user.userprofile.last_activity|timesince }} назад
          </small>
          {% endif %}  
      </p>

        </div>


        </div>
       <div style="margin-top: 45px;"></div>
        <hr>

         
        
      <div class="messagepole" id="messagepole">

      

    {% for mess in allmessages %}
    {% if mess.user == request.user %}
    {% if mess.useryou == userobjchat.user %}

 
  <br>
      <article class="mymessage">

     <div class="imgandmsg">   
<p class="nameclassmsg">
  {{ mess.datamessage|date:"H:i" }} </p> 

          <img class="img-fluid imgchatsmallmy" 
          src="{{ mess.user.userprofile.avatar.url }}">
          <a class="menuclassmessage" 
          href="/chatdel/{{ mess.id }}/">
            <i class="fas fa-trash-alt"></i>
          </a>
     </div>
          
<div class="messageclass">{{ mess.message|linebreaks }}</div>
      </article> <br><br><br><br><br>


      
      
        {% endif %}
      {% else %}

        {% if mess.user == userobjchat.user %}
        {% if mess.useryou == request.user %}
<br>
      <article class="yourmessage">
        
<div class="imgandmsgyour">
        
<img class="img-fluid imgchatsmall imgchatsmallyour" 
      src="{{ mess.user.userprofile.avatar.url }}">
      
      <p class="nameimgmsgyour">
       
    {{ mess.datamessage|date:"H:i" }}</p>

      
</div>

<div class="msgyourclass">{{ mess.message|linebreaks }}</div>
      
      </article>
      <br><br><br><br><br><br>
      
      {% endif %} <!-- mess.useryou = request.user -->

      {% endif %}
      {% endif %}
      {% endfor %}
      
      


<br><br>
      </div> <!-- ../ MessagePole -->

      <script> 
      // Делает скролл чата всегда внизу
var messageBody = document.querySelector('.messagepole');
      messageBody.scrollTop = messageBody.scrollHeight - messageBody.clientHeight;
      </script>
        


            <div class="formachat">
          <form action="" method="post" id="formmessage" 
          enctype='multipart/form-data'>
          {% csrf_token %}
          

          <!-- <select class="hiddentest" 
          name="useryou" id="id_useryou" required>
  <option value="1">{{ userobjchat.user }}</option>
  </select> -->

          <input type="hidden" for="id_message" 
          name="runmessagehtml" id="hiddeninputmsg">
            <textarea wrap="soft | hard" class="textmessage" 
            name="message" id="id_message"></textarea>
          <input type="hidden" name="messagedohtml">


<!-- Выберает useryou -->
<div class="hiddentest">
<tr><th><label for="id_useryou">Useryou:</label></th><td>
<select name="useryou" id="id_useryou" required>

  <option 
  value="{{ userobjchat.user.id }}" 
  selected>{{ userobjchat.user }}
  </option>


</select></td></tr>
</div>


            


            <button name="submit" type="submit" id="submit"
            class="buttonmessage">
              <i class="fas fa-arrow-alt-circle-right circlemessage"></i>
            </button>



  

          </form>
          </div>
      </div>

        <div class="col-lg-3 col-md-12 col-xs-12">
          <div class="listmessages">
            
  
            {% for d in chatstory %}
{% if d.user in request.user.userprofile.allmessagesstory.all %}
          <div class="allchat">
          <p>
<a href="{{ d.user_get_absolute_url }}chat/">
          {{ d.user.get_full_name }} 

  </a>
  
{% if d.user in request.user.userprofile.messagedo.all %}
<p class="inmessage">
  Пропущенное сообщение
</p>
{% endif %}
          </p>
          </div>
          <hr>

          {% endif %}
          {% endfor %}
  

          </div>
 
        </div>
          
        

      </div>
    </div>